site_name: Learn about Zotero
site_url: https://b-benja.github.io/Bens_Zotero/
site_author: Benjamin Buettner

repo_name: B-Benja/Bens_Zotero
repo_url: https://github.com/B-Benja/Bens_Zotero

nav:
    - zotero/index.md
    - zotero/first-steps.md
    - zotero/organizing-content.md
    - zotero/adding-citations.md
    - zotero/syncing.md
    - zotero/useful-plugins.md
 
theme:
 name: material
 features:
   - navigation.tabs
   - navigation.tabs.sticky
    - navigation.instant
 palette:
   - media: "(prefers-color-scheme: light)" 
     scheme: default
     accent: pink
     toggle:
       icon: material/weather-night
       name: Welcome to the dark side
   - media: "(prefers-color-scheme: dark)" 
     scheme: slate
     primary: pink
     toggle:
       icon: material/weather-sunny
       name: Let there be light


copyright: Copyright &copy; Benjamin Buettner with &hearts;
